# Generated by Django 5.2.7 on 2025-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.TextField(db_index=True, unique=True)),
                ('clerk_user_name', models.TextField()),
                ('clerk_user_email', models.EmailField(max_length=254)),
                ('clerk_user_available_storage_gb', models.BigIntegerField()),
                ('clerk_user_used_storage_gb', models.BigIntegerField()),
                ('clerk_user_created_at', models.DateTimeField(auto_now_add=True)),
                ('clerk_user_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
