# Generated by Django 5.2.7 on 2025-11-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('file_name', models.TextField()),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_extension', models.TextField()),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('celery_task_ID', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Backend.clerkuserprofile')),
            ],
        ),
    ]
