# Generated by Django 5.2.7 on 2025-11-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_size',
            field=models.FloatField(),
        ),
    ]
