# Generated by Django 5.2.7 on 2025-11-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_filemodel_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkuserprofile',
            name='clerk_user_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ADVANCED', 'Advanced')], default='FREE', max_length=50),
        ),
    ]
