# Generated by Django 5.2.7 on 2025-12-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_clerkuserprofile_clerk_user_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.FloatField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isfolder', models.BooleanField(default=False)),
                ('is_root_folder', models.BooleanField(default=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_extension', models.TextField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('celery_task_ID', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Backend.clerkuserprofile')),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.filefoldermodel')),
            ],
            options={
                'verbose_name_plural': 'FileFolderModels',
            },
        ),
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_root_folder', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_items', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='Backend.clerkuserprofile')),
                ('parentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Backend.foldermodel')),
            ],
        ),
        migrations.AddField(
            model_name='filemodel',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_name', to='Backend.foldermodel'),
        ),
    ]
