# Generated by Django 5.2.7 on 2025-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_filefoldermodel_foldermodel_filemodel_parentfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefoldermodel',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='PENDING', max_length=50, null=True),
        ),
    ]
