# Generated by Django 5.2.7 on 2025-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_filefoldermodel_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefoldermodel',
            name='celery_task_ID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
