# Generated by Django 5.2.7 on 2025-12-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_filefoldermodel_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefoldermodel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filefoldermodel',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
