# Generated by Django 5.2.7 on 2026-01-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_filefoldermodel_is_favorite_filefoldermodel_is_trash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filefoldermodel',
            old_name='is_root_folder',
            new_name='is_root',
        ),
    ]
