# Generated by Django 5.2.7 on 2026-01-28 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_rename_is_root_folder_filefoldermodel_is_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldermodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='foldermodel',
            name='parentID',
        ),
        migrations.RemoveField(
            model_name='clerkuserprofile',
            name='clerk_user_available_storage_gb',
        ),
        migrations.RemoveField(
            model_name='clerkuserprofile',
            name='clerk_user_used_storage_gb',
        ),
        migrations.CreateModel(
            name='ClerkUserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_available_storage', models.BigIntegerField()),
                ('clerk_user_used_storage', models.BigIntegerField()),
                ('total_image_storage', models.BigIntegerField()),
                ('total_document_storage', models.BigIntegerField()),
                ('total_other_storage', models.BigIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_stats', to='Backend.clerkuserprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.DeleteModel(
            name='FolderModel',
        ),
    ]
