# Generated by Django 5.2.7 on 2026-01-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_remove_foldermodel_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerkuserstorage',
            old_name='clerk_user_available_storage',
            new_name='clerk_user_storage_limit',
        ),
    ]
