# Generated by Django 5.2.7 on 2026-01-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_rename_clerk_user_available_storage_clerkuserstorage_clerk_user_storage_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkuserstorage',
            name='clerk_user_storage_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clerkuserstorage',
            name='clerk_user_used_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clerkuserstorage',
            name='total_document_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clerkuserstorage',
            name='total_image_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clerkuserstorage',
            name='total_other_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filefoldermodel',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
