# Generated by Django 5.2.7 on 2026-01-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_alter_clerkuserstorage_clerk_user_storage_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefoldermodel',
            name='size',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
