# Generated by Django 5.2.7 on 2026-01-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_alter_filefoldermodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefoldermodel',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
