# Generated by Django 5.2.7 on 2026-01-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_alter_filefoldermodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkuserstorage',
            name='storage_percentage_used',
            field=models.FloatField(default=0.0),
        ),
    ]
