# Generated by Django 5.2.7 on 2026-02-11 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_clerkuserstorage_storage_percentage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkuserprofile',
            name='clerk_user_profile_img',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFCzxivJXCZk0Kk8HsHujTO3Olx0ngytPrWw&s'),
        ),
        migrations.CreateModel(
            name='FileFolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('ADMIN', 'Admin')], default='VIEW', max_length=100)),
                ('permission_granted_at', models.DateTimeField(auto_now_add=True)),
                ('fileFolder_Instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folder_permissions', to='Backend.filefoldermodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_be_granted_with_permission', to='Backend.clerkuserprofile')),
            ],
        ),
    ]
