# Generated by Django 5.2.7 on 2026-02-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_clerkuserprofile_clerk_user_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkuserprofile',
            name='clerk_user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
