# Generated by Django 5.2.7 on 2026-02-16 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_alter_clerkuserprofile_clerk_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareable_id', models.UUIDField(db_index=True)),
                ('view_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=100)),
                ('data_type', models.CharField(choices=[('FILE', 'File'), ('FOLDER', 'Folder')], default='FILE', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.TextField()),
                ('access_count', models.IntegerField(default=0)),
                ('max_count', models.IntegerField(blank=True, null=True)),
                ('file_folder_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folder', to='Backend.filefoldermodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_owner', to='Backend.clerkuserprofile')),
            ],
        ),
    ]
