# Generated by Django 5.2.7 on 2026-02-16 02:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='shareable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
