# Generated by Django 5.2.7 on 2026-02-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_alter_sharelink_shareable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='password_hash',
            field=models.TextField(null=True),
        ),
    ]
