# Generated by Django 5.2.7 on 2026-03-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_alter_sharelink_password_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filefolderpermission',
            unique_together={('fileFolder_Instance_id', 'user_id')},
        ),
    ]
