# Generated by Django 5.2.7 on 2026-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_alter_filefolderpermission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefoldermodel',
            name='path',
            field=models.TextField(null=True ,blank=True, default=None),
        ),
    ]
