# Generated by Django 5.2.7 on 2026-03-19 06:47

from django.db import migrations

def update_path_for_exisitng_records(apps, schema_editor):
    # getting the access to our exisitng model to perform manuplations
    FileFolder = apps.get_model('Backend', 'FileFolderModel')

    # Find records that claim to be roots AND actually have no parent
    roots = FileFolder.objects.filter(parentFolder__isnull=True)
    #updating path of all the parent fileFolders...........
    roots.update(path=None , is_root = True)

    current_level_parents = roots
    while current_level_parents.exists():
        next_level_parents = FileFolder.objects.none()
        for parent in current_level_parents:
            children = FileFolder.objects.filter(parentFolder = parent)
            if children.exists():
                new_path = ''
                if parent.path is not None:
                    new_path = f'{parent.path}/{parent.id}'
                else:
                     new_path = parent.id
                
                children.update(path = new_path , is_root = False)
                next_level_parents |= children
            
        current_level_parents = next_level_parents


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0022_filefoldermodel_path'),
    ]

    operations = [
        migrations.RunPython(update_path_for_exisitng_records),
    ]
