# Generated by Django 5.2.7 on 2026-03-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_auto_20260319_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefoldermodel',
            name='type_of_file_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
