# Generated by Django 5.2.7 on 2026-03-22 15:23

from django.db import migrations

def update_type_of_file_folder(apps, schema_editor):
    FileFolder = apps.get_model('Backend', 'FileFolderModel')

    # Update existing records based on the presence of file_url
    for record in FileFolder.objects.all():
        if record.file_url:
            # Check file extension
            if record.file_extension.lower().endswith(('.png', '.jpeg', '.jpg', '.gif', '.bmp', '.webp')):
                record.type_of_file_folder = 'image'
        else:
            record.type_of_file_folder = None
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0024_filefoldermodel_type_of_file_folder'),
    ]

    operations = [
        migrations.RunPython(update_type_of_file_folder),
    ]
