# Generated by Django 5.2.7 on 2026-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0025_auto_20260322_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefoldermodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
