# Generated by Django 5.2.7 on 2026-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0026_filefoldermodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefoldermodel',
            name='imageKit_file_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
