# Generated by Django 5.2.7 on 2026-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0027_filefoldermodel_imagekit_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefoldermodel',
            name='path',
            field=models.TextField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
