# Generated by Django 5.2.7 on 2026-04-10 16:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0028_alter_filefoldermodel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefoldermodel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='filefoldermodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='file_search_vector_idx'),
        ),
    ]
