# Generated by Django 5.2.7 on 2026-04-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0030_filefoldermodel_search_vector_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql = """
            CREATE OR REPLACE FUNCTION update_file_search_vector() RETURNS trigger AS $$
            BEGIN
                new.search_vector:=
                    setweight(to_tsvector('pg_catalog.english', coalesce(new.name, '')), 'A') ||
                    setweight(to_tsvector('pg_catalog.english', coalesce(new.description, '')), 'B');
                RETURN new;
            END
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS update_file_search_vector();"
        ),
        migrations.RunSQL(
            sql = """
            CREATE TRIGGER update_file_search_vector
            BEFORE INSERT OR UPDATE ON "Backend_filefoldermodel"
            FOR EACH ROW EXECUTE FUNCTION update_file_search_vector();
            """,
            reverse_sql="""DROP TRIGGER IF EXISTS file_search_update_trigger ON "Backend_filefoldermodel";"""
        ),
        migrations.RunSQL(
            sql = """
            UPDATE "Backend_filefoldermodel" SET search_vector = 
                setweight(to_tsvector('pg_catalog.english', coalesce(name, '')), 'A') ||
                setweight(to_tsvector('pg_catalog.english', coalesce(description, '')), 'B');
            """,
            reverse_sql="" 
        )
    ]
