# Generated by Django 5.2.7 on 2026-04-24 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0031_auto_20260410_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefoldermodel',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filefoldermodel',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResourceSecurityPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encypted_password', models.TextField(blank=True, null=True)),
                ('security_pass_key', models.TextField(blank=True, null=True)),
                ('file_folder_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_policies', to='Backend.filefoldermodel')),
            ],
        ),
    ]
