# Generated by Django 5.2.7 on 2026-04-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0032_filefoldermodel_is_critical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesecuritypolicies',
            name='security_pass_key',
        ),
        migrations.CreateModel(
            name='SecuritySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.TextField()),
                ('created_at_or_updated_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('file_folder_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_session_file_folder_instance', to='Backend.filefoldermodel')),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_user_session', to='Backend.clerkuserprofile')),
            ],
        ),
    ]
