# Generated by Django 5.2.7 on 2026-04-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0033_remove_resourcesecuritypolicies_security_pass_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefoldermodel',
            name='is_critical',
        ),
        migrations.RemoveField(
            model_name='filefoldermodel',
            name='is_password_protected',
        ),
        migrations.AddField(
            model_name='resourcesecuritypolicies',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcesecuritypolicies',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
    ]
