# Generated by Django 5.2.7 on 2026-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0034_remove_filefoldermodel_is_critical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesecuritypolicies',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcesecuritypolicies',
            name='session_duration',
            field=models.IntegerField(default=1),
        ),
    ]
