# Generated by Django 5.2.7 on 2026-10-05 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0035_resourcesecuritypolicies_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_encryption_key_salt', models.TextField()),
                ('user_public_key', models.TextField()),
                ('user_encrypted_private_key', models.TextField()),
                ('user_encrypted_private_key_nonce', models.TextField()),
                ('user_encrypted_master_key', models.TextField()),
                ('user_encrypted_master_key_nonce', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to='Backend.clerkuserprofile')),
            ],
        ),
    ]
